#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse
import pandas as pd

# Import from nlp_preprocessing
import nlp_preprocessing
from nlp_preprocessing.lib import clean_text

if __name__ == '__main__':
    usage = '%(prog)s'
    description = 'nlp_preprocessing_description'
    # https://docs.python.org/3/library/argparse.html
    # https://docs.python.org/3/howto/argparse.html
    parser = argparse.ArgumentParser(description=description, usage=usage)
    args = parser.parse_args()
    folder_source, _ = split(nlp_preprocessing.__file__)
    df = pd.read_csv('{}/data/data'.format(folder_source), sep=",", header=None, names=['text'])
    print('  nlp_preprocessing/data/data Loaded')

    res = df.text.apply(clean_text)
    res.to_csv('out.csv', index=False)
    print('==> out.csv MADE ')
    print('    shape is {}'.format(res.shape))
